zuul:
  routes:
    youinvoice:
      path: /**
      url: http://localhost:8080     
spring:
  application:
    name: youinvoice-zuul-gateway
ribbon: 
  eureka:
    enabled: false
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
